

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    '''
    A class to provide information about the GUI layout
    '''
    def setupUi(self, MainWindow):
        '''
        Function to house information and create the GUI
        :param MainWindow: the GUI
        '''
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 547)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_Dealer = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_Dealer.setGeometry(QtCore.QRect(10, 10, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_Dealer.setFont(font)
        self.label_Dealer.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_Dealer.setObjectName("label_Dealer")
        self.label_Player = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_Player.setGeometry(QtCore.QRect(610, 10, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_Player.setFont(font)
        self.label_Player.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_Player.setObjectName("label_Player")
        self.label_Wins = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_Wins.setGeometry(QtCore.QRect(300, 10, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_Wins.setFont(font)
        self.label_Wins.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_Wins.setObjectName("label_Wins")
        self.line_H = QtWidgets.QFrame(parent=self.centralwidget)
        self.line_H.setGeometry(QtCore.QRect(0, 50, 781, 20))
        self.line_H.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_H.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_H.setObjectName("line_H")
        self.line_V = QtWidgets.QFrame(parent=self.centralwidget)
        self.line_V.setGeometry(QtCore.QRect(380, 70, 20, 381))
        self.line_V.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_V.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_V.setObjectName("line_V")
        self.frame_Dealer1 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_Dealer1.setGeometry(QtCore.QRect(40, 100, 101, 151))
        self.frame_Dealer1.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_Dealer1.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_Dealer1.setObjectName("frame_Dealer1")
        self.label_DCard1 = QtWidgets.QLabel(parent=self.frame_Dealer1)
        self.label_DCard1.setGeometry(QtCore.QRect(20, 10, 61, 131))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_DCard1.setFont(font)
        self.label_DCard1.setText("")
        self.label_DCard1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_DCard1.setObjectName("label_DCard1")
        self.frame_Dealer2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_Dealer2.setGeometry(QtCore.QRect(150, 100, 101, 151))
        self.frame_Dealer2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_Dealer2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_Dealer2.setObjectName("frame_Dealer2")
        self.label_DCard2 = QtWidgets.QLabel(parent=self.frame_Dealer2)
        self.label_DCard2.setGeometry(QtCore.QRect(20, 10, 61, 131))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_DCard2.setFont(font)
        self.label_DCard2.setText("")
        self.label_DCard2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_DCard2.setObjectName("label_DCard2")
        self.frame_Dealer3 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_Dealer3.setGeometry(QtCore.QRect(260, 100, 101, 151))
        self.frame_Dealer3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_Dealer3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_Dealer3.setObjectName("frame_Dealer3")
        self.label_DCard3 = QtWidgets.QLabel(parent=self.frame_Dealer3)
        self.label_DCard3.setGeometry(QtCore.QRect(20, 10, 61, 131))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_DCard3.setFont(font)
        self.label_DCard3.setText("")
        self.label_DCard3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_DCard3.setObjectName("label_DCard3")
        self.frame_Dealer4 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_Dealer4.setGeometry(QtCore.QRect(40, 260, 101, 151))
        self.frame_Dealer4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_Dealer4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_Dealer4.setObjectName("frame_Dealer4")
        self.label_DCard4 = QtWidgets.QLabel(parent=self.frame_Dealer4)
        self.label_DCard4.setGeometry(QtCore.QRect(20, 10, 61, 131))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_DCard4.setFont(font)
        self.label_DCard4.setText("")
        self.label_DCard4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_DCard4.setObjectName("label_DCard4")
        self.frame_Dealer5 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_Dealer5.setGeometry(QtCore.QRect(150, 260, 101, 151))
        self.frame_Dealer5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_Dealer5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_Dealer5.setObjectName("frame_Dealer5")
        self.label_DCard5 = QtWidgets.QLabel(parent=self.frame_Dealer5)
        self.label_DCard5.setGeometry(QtCore.QRect(20, 10, 61, 131))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_DCard5.setFont(font)
        self.label_DCard5.setText("")
        self.label_DCard5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_DCard5.setObjectName("label_DCard5")
        self.frame_Dealer6 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_Dealer6.setGeometry(QtCore.QRect(260, 260, 101, 151))
        self.frame_Dealer6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_Dealer6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_Dealer6.setObjectName("frame_Dealer6")
        self.label_DCard6 = QtWidgets.QLabel(parent=self.frame_Dealer6)
        self.label_DCard6.setGeometry(QtCore.QRect(20, 10, 61, 131))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_DCard6.setFont(font)
        self.label_DCard6.setText("")
        self.label_DCard6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_DCard6.setObjectName("label_DCard6")
        self.frame_Player1 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_Player1.setGeometry(QtCore.QRect(420, 100, 101, 151))
        self.frame_Player1.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_Player1.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_Player1.setObjectName("frame_Player1")
        self.label_PCard1 = QtWidgets.QLabel(parent=self.frame_Player1)
        self.label_PCard1.setGeometry(QtCore.QRect(20, 10, 61, 131))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_PCard1.setFont(font)
        self.label_PCard1.setText("")
        self.label_PCard1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_PCard1.setObjectName("label_PCard1")
        self.frame_Player2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_Player2.setGeometry(QtCore.QRect(530, 100, 101, 151))
        self.frame_Player2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_Player2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_Player2.setObjectName("frame_Player2")
        self.label_PCard2 = QtWidgets.QLabel(parent=self.frame_Player2)
        self.label_PCard2.setGeometry(QtCore.QRect(20, 10, 61, 131))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_PCard2.setFont(font)
        self.label_PCard2.setText("")
        self.label_PCard2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_PCard2.setObjectName("label_PCard2")
        self.frame_Player3 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_Player3.setGeometry(QtCore.QRect(640, 100, 101, 151))
        self.frame_Player3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_Player3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_Player3.setObjectName("frame_Player3")
        self.label_PCard3 = QtWidgets.QLabel(parent=self.frame_Player3)
        self.label_PCard3.setGeometry(QtCore.QRect(20, 10, 61, 131))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_PCard3.setFont(font)
        self.label_PCard3.setText("")
        self.label_PCard3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_PCard3.setObjectName("label_PCard3")
        self.frame_Player4 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_Player4.setGeometry(QtCore.QRect(420, 260, 101, 151))
        self.frame_Player4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_Player4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_Player4.setObjectName("frame_Player4")
        self.label_PCard4 = QtWidgets.QLabel(parent=self.frame_Player4)
        self.label_PCard4.setGeometry(QtCore.QRect(20, 10, 61, 131))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_PCard4.setFont(font)
        self.label_PCard4.setText("")
        self.label_PCard4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_PCard4.setObjectName("label_PCard4")
        self.frame_Player5 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_Player5.setGeometry(QtCore.QRect(530, 260, 101, 151))
        self.frame_Player5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_Player5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_Player5.setObjectName("frame_Player5")
        self.label_PCard5 = QtWidgets.QLabel(parent=self.frame_Player5)
        self.label_PCard5.setGeometry(QtCore.QRect(20, 10, 61, 131))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_PCard5.setFont(font)
        self.label_PCard5.setText("")
        self.label_PCard5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_PCard5.setObjectName("label_PCard5")
        self.frame_Player6 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_Player6.setGeometry(QtCore.QRect(640, 260, 101, 151))
        self.frame_Player6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_Player6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_Player6.setObjectName("frame_Player6")
        self.label_PCard6 = QtWidgets.QLabel(parent=self.frame_Player6)
        self.label_PCard6.setGeometry(QtCore.QRect(20, 10, 61, 131))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_PCard6.setFont(font)
        self.label_PCard6.setText("")
        self.label_PCard6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_PCard6.setObjectName("label_PCard6")
        self.pushButton_Exit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_Exit.setGeometry(QtCore.QRect(50, 450, 121, 61))
        self.pushButton_Exit.setObjectName("pushButton_Exit")
        self.pushButton_OK = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_OK.setGeometry(QtCore.QRect(500, 450, 121, 61))
        self.pushButton_OK.setObjectName("pushButton_OK")
        self.pushButton_Hit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_Hit.setGeometry(QtCore.QRect(640, 450, 121, 61))
        self.pushButton_Hit.setObjectName("pushButton_Hit")
        self.label_WinLose = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_WinLose.setGeometry(QtCore.QRect(310, 460, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_WinLose.setFont(font)
        self.label_WinLose.setText("")
        self.label_WinLose.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_WinLose.setObjectName("label_WinLose")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        '''
        function to set up the GUI
        '''
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_Dealer.setText(_translate("MainWindow", "Dealer"))
        self.label_Player.setText(_translate("MainWindow", "Player"))
        self.label_Wins.setText(_translate("MainWindow", "Wins:"))
        self.pushButton_Exit.setText(_translate("MainWindow", "Exit"))
        self.pushButton_OK.setText(_translate("MainWindow", "OK"))
        self.pushButton_Hit.setText(_translate("MainWindow", "Hit (Start)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
